### PR TITLE
Do not create parent directory objects and bucket for new directories

### LINKED ISSUE #135: GCS connector requires storage.buckets.get permissions to list entities at the bucket root
The `StorageObjectAdmin` Role is not sufficient to able to use the GCS connector to perform the following operations
1) ls at the root ->` hadoop fs -ls gs://BUCKET/`
2) ls on an objet that does not exist -> `hadoop fs -ls gs://BUCKET/{INVALID_OBJECT}`

The exception is pasted further down.

The same is not the case for `gsutil`.
`gsutil ls gs://BUCKET/` and `gsutil ls gs://BUCKET/{INVALID_OBJECT}` works fine.

It looks like the connector falls back to perform a `bucket.get` operation. Creating a custom role with `storage.bucket.get` + `StorageObjectAdmin` gets the connector working properly again.

Is this intended behaviour? If so, would be nice to document.

Here's the stack trace.

```
Exception in thread "main" java.io.IOException: Multiple IOExceptions.
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageExceptions.createCompositeException(GoogleCloudStorageExceptions.java:60)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfos(GoogleCloudStorageImpl.java:1612)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getFileInfosRaw(GoogleCloudStorageFileSystem.java:1298)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.listFileInfo(GoogleCloudStorageFileSystem.java:1077)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.listStatus(GoogleHadoopFileSystemBase.java:1329)
	at org.apache.hadoop.fs.generic.wrapper.GenericWrappedFileSystem.listStatus(GenericWrappedFileSystem.java:199)
	at com.hortonworks.TestSeek.run(TestSeek.java:89)
	at com.hortonworks.TestSeek.main(TestSeek.java:30)
	Suppressed: java.io.IOException: Error getting Bucket: : bucket: BUCKET_NAME
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.wrapException(GoogleCloudStorageImpl.java:1832)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl$11.onFailure(GoogleCloudStorageImpl.java:1575)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:54)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:50)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:223)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.flushIfPossible(BatchHelper.java:117)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.flush(BatchHelper.java:130)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfos(GoogleCloudStorageImpl.java:1609)
		... 6 more
	Caused by: java.io.IOException: {"code":403,"errors":[{"domain":"global","message":"SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET_NAME.","reason":"forbidden"}],"message":"SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET_NAME."}
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl$11.onFailure(GoogleCloudStorageImpl.java:1573)
		... 14 more
	Suppressed: java.io.IOException: Error getting Bucket: : bucket: BUCKET_NAME
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.wrapException(GoogleCloudStorageImpl.java:1832)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl$11.onFailure(GoogleCloudStorageImpl.java:1575)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:54)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:50)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:223)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.flushIfPossible(BatchHelper.java:117)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.flush(BatchHelper.java:130)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfos(GoogleCloudStorageImpl.java:1609)
		... 6 more
	Caused by: java.io.IOException: {"code":403,"errors":[{"domain":"global","message":"SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET_NAME.","reason":"forbidden"}],"message":"SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET_NAME."}
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl$11.onFailure(GoogleCloudStorageImpl.java:1573)
		... 14 more
```

### PR DESCRIPTION
**Pull request by medb**
1. Instead of creating parent directory objects rely on implicit directory inference.
2. Do not create bucket if it does not exist - this will require that buckets to be created explicitly.

Fixes #135

### CODE REVIEW

File: gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/WebHdfsIntegrationTest.java [hunk 1]
```diff
@@ -146,12 +146,31 @@ public void testGetDefaultReplication()
...
+  }
+
+  /**
+   * Validates that we cannot open an object in non-existent bucket.
+   *
+   * <p>Note: WebHDFS throws IOException (Internal Server Error (error code=500))
+   */
+  @Test
+  @Override
+  public void testOpenInNonExistentBucket() throws IOException {
```
Comment (hongyegong) [inline gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/WebHdfsIntegrationTest.java:172]: Given we added this case, should we also have a test here like named something like testOpenNonExistentObjectInExistentBucket?

File: gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java [hunk 2]
```diff
@@ -231,21 +233,34 @@ public WritableByteChannel create(URI path, CreateFileOptions options) throws IO
...
-    if (options.isEnsureNoDirectoryConflict()
-        && getFileInfoInternal(resourceId.toDirectoryId(), /* inferImplicitDirectories */ true)
-            .exists()) {
-      throw new FileAlreadyExistsException("A directory with that name exists: " + path);
+    // Before creating a top-level directory we need to check if there are no conflicting files
+    // with the same name as any subdirectory
+    if (options.isEnsureNoConflictingItems()) {
+      // Asynchronously check if a directory with the same name exists.
+      StorageResourceId dirId = resourceId.toDirectoryId();
+      Future<Boolean> conflictingDirExist =
```
Comment (hongyegong) [inline gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java:241]: Since we already use Executor here, is it a better practice to throw both of two tasks into threadpool and let them run?

File: gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java [hunk 3]
```diff
@@ -421,64 +436,49 @@ public void mkdirs(URI path) throws IOException {
...
-      }
+    // Before creating a top-level directory we need to check if there are no conflicting files
+    // with the same name as any subdirectory
+    if (options.isEnsureNoConflictingItems()) {
+      checkNoFilesConflictingWithDirs(resourceId);
     }
 
-    if (!checkNotNull(bucketInfo, "bucketInfo should not be null").exists()) {
-      gcs.createBucket(bucketInfo.getBucketName());
+    // Create only a top-level directory because subdirectories will be inferred
```
Comment (hongyegong) [inline gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java:470]: I am a little bit confused by the name here, what exactly does top-level here mean?
My understanding is if we are trying to create `gs://foo/bar/zoo/` then top level is `gs://foo`？But this understanding doesn't seem to match with what code is doing?

File: gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/WebHdfsIntegrationTest.java (hunk 1 above)
Comment (medb) [reply gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/WebHdfsIntegrationTest.java:172]: Done. Added above.

File: gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java (hunk 2 above)
Comment (medb) [reply gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java:241]: We use executor only when we need to parallelize some requests - running requests asynchronously in executor and immediately blocking on its execution should be not faster than just executing directly.

File: gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java (hunk 3 above)
Comment (medb) [reply gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java]: Good point, reworded.

File: gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java [hunk 4]
```diff
@@ -464,6 +464,13 @@ public void createBucket(String bucketName, CreateBucketOptions options) throws
     } catch (InterruptedException e) {
       Thread.currentThread().interrupt();
       throw new IOException("Failed to create bucket", e);
+    } catch (IOException e) {
+      if (ApiErrorExtractor.INSTANCE.itemAlreadyExists(e)) {
+        throw (FileAlreadyExistsException)
```
Comment (hongyegong) [inline gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java:469]: Unnecessary cast?

**Review by hongyegong — APPROVED** [review]

File: gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java (hunk 4 above)
Comment (medb) [reply gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java:469]: No, it's necessary -`initCause` returns `Throwable`.
